services:
  27d88f96-90d8-4aa5-a4f6-4c697036a8eb:
    container_name: microservice-27d88f96-90d8-4aa5-a4f6-4c697036a8eb
    build:
      context: ./services/service-27d88f96-90d8-4aa5-a4f6-4c697036a8eb
      dockerfile: ../../dockerfiles/Dockerfile.27d88f96-90d8-4aa5-a4f6-4c697036a8eb
    ports:
      - 45497:3000
    environment:
      SERVICE_NAME: leertabla
      SERVICE_TYPE: roble
      TABLE_NAME: microservices
      ROBLE_MODE: current
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - microservices-network
  b348187f-4a8b-4c5b-85a7-6e1a72e9d1f4:
    container_name: microservice-b348187f-4a8b-4c5b-85a7-6e1a72e9d1f4
    build:
      context: ./services/service-b348187f-4a8b-4c5b-85a7-6e1a72e9d1f4
      dockerfile: ../../dockerfiles/Dockerfile.b348187f-4a8b-4c5b-85a7-6e1a72e9d1f4
    ports:
      - 45046:3000
    environment:
      SERVICE_NAME: leerpersonas
      SERVICE_TYPE: roble
      TABLE_NAME: personas
      ROBLE_MODE: different
      ROBLE_SERVICE_CONTRACT: micro_services_c9831a5f3a
      ROBLE_SERVICE_EMAIL: personas@gmail.com
      ROBLE_SERVICE_PASSWORD: Contraseña123!
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - microservices-network
  3d9238d2-e440-4b36-b1bf-81de7e5aef27:
    container_name: microservice-3d9238d2-e440-4b36-b1bf-81de7e5aef27
    build:
      context: ./services/service-3d9238d2-e440-4b36-b1bf-81de7e5aef27
      dockerfile: ../../dockerfiles/Dockerfile.3d9238d2-e440-4b36-b1bf-81de7e5aef27
    ports:
      - 45722:3000
    environment:
      SERVICE_NAME: personas
      SERVICE_TYPE: roble
      TABLE_NAME: personas
      ROBLE_MODE: different
      ROBLE_SERVICE_CONTRACT: micro_services_c9831a5f3a
      ROBLE_SERVICE_EMAIL: personas@gmail.com
      ROBLE_SERVICE_PASSWORD: Contraseña123!
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - microservices-network
  87fd15ba-b587-44f5-97bb-1e41b5e65760:
    container_name: microservice-87fd15ba-b587-44f5-97bb-1e41b5e65760
    build:
      context: ./services/service-87fd15ba-b587-44f5-97bb-1e41b5e65760
      dockerfile: ../../dockerfiles/Dockerfile.87fd15ba-b587-44f5-97bb-1e41b5e65760
    ports:
      - 45504:3000
    environment:
      SERVICE_NAME: dsadsa
      SERVICE_TYPE: roble
      TABLE_NAME: microservices
      ROBLE_MODE: current
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
