services:
  88be4d2f-a722-45aa-8302-1849f16499a5:
    container_name: microservice-88be4d2f-a722-45aa-8302-1849f16499a5
    build:
      context: ./services/service-88be4d2f-a722-45aa-8302-1849f16499a5
      dockerfile: ../../dockerfiles/Dockerfile.88be4d2f-a722-45aa-8302-1849f16499a5
    ports:
      - 45134:3000
    environment:
      SERVICE_NAME: prueba roble
      SERVICE_TYPE: roble
      TABLE_NAME: microservices
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
