version: 3.8
services:
  3e665c0a-23cd-407f-9253-532d5e0ad5ff:
    container_name: microservice-3e665c0a-23cd-407f-9253-532d5e0ad5ff
    build:
      context: .
      dockerfile: Dockerfile.3e665c0a-23cd-407f-9253-532d5e0ad5ff
    ports:
      - 45629:3000
    environment:
      SERVICE_NAME: Mi prueba
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  04e9adba-81e3-4bd8-9c29-f70ad248f7c7:
    container_name: microservice-04e9adba-81e3-4bd8-9c29-f70ad248f7c7
    build:
      context: .
      dockerfile: Dockerfile.04e9adba-81e3-4bd8-9c29-f70ad248f7c7
    ports:
      - 45837:3000
    environment:
      SERVICE_NAME: jud
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  5236c556-2f5c-4a53-8b5d-51c88ea2338b:
    container_name: microservice-5236c556-2f5c-4a53-8b5d-51c88ea2338b
    build:
      context: .
      dockerfile: Dockerfile.5236c556-2f5c-4a53-8b5d-51c88ea2338b
    ports:
      - 45860:3000
    environment:
      SERVICE_NAME: jud
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  c926faf2-2cb6-4df2-b657-0b4cd56c1d66:
    container_name: microservice-c926faf2-2cb6-4df2-b657-0b4cd56c1d66
    build:
      context: .
      dockerfile: Dockerfile.c926faf2-2cb6-4df2-b657-0b4cd56c1d66
    ports:
      - 45716:3000
    environment:
      SERVICE_NAME: jud
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  f6ad4314-fb9e-40a1-b38f-99c794cdeb25:
    container_name: microservice-f6ad4314-fb9e-40a1-b38f-99c794cdeb25
    build:
      context: .
      dockerfile: Dockerfile.f6ad4314-fb9e-40a1-b38f-99c794cdeb25
    ports:
      - 45202:3000
    environment:
      SERVICE_NAME: jud
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  e820b511-805f-4e44-b27e-17eba34e4fc3:
    container_name: microservice-e820b511-805f-4e44-b27e-17eba34e4fc3
    build:
      context: .
      dockerfile: Dockerfile.e820b511-805f-4e44-b27e-17eba34e4fc3
    ports:
      - 45222:3000
    environment:
      SERVICE_NAME: jud
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  35ddc099-05b2-47b4-8e77-bcbfb67dc11f:
    container_name: microservice-35ddc099-05b2-47b4-8e77-bcbfb67dc11f
    build:
      context: .
      dockerfile: Dockerfile.35ddc099-05b2-47b4-8e77-bcbfb67dc11f
    ports:
      - 45771:3000
    environment:
      SERVICE_NAME: judithhh
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  2a7f2d73-45c0-487b-8739-d73ccfadb7fc:
    container_name: microservice-2a7f2d73-45c0-487b-8739-d73ccfadb7fc
    build:
      context: .
      dockerfile: Dockerfile.2a7f2d73-45c0-487b-8739-d73ccfadb7fc
    ports:
      - 45475:3000
    environment:
      SERVICE_NAME: hoy
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  4f2e4e2c-dce1-43ae-a70d-ba54d56fb4e1:
    container_name: microservice-4f2e4e2c-dce1-43ae-a70d-ba54d56fb4e1
    build:
      context: .
      dockerfile: Dockerfile.4f2e4e2c-dce1-43ae-a70d-ba54d56fb4e1
    ports:
      - 45562:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  37b05a95-2fe5-4ace-86fc-780598133762:
    container_name: microservice-37b05a95-2fe5-4ace-86fc-780598133762
    build:
      context: .
      dockerfile: Dockerfile.37b05a95-2fe5-4ace-86fc-780598133762
    ports:
      - 45841:3000
    environment:
      SERVICE_NAME: nuevo
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  e1aa9dd9-570e-4a1d-9505-a9f25f5cf6b9:
    container_name: microservice-e1aa9dd9-570e-4a1d-9505-a9f25f5cf6b9
    build:
      context: .
      dockerfile: Dockerfile.e1aa9dd9-570e-4a1d-9505-a9f25f5cf6b9
    ports:
      - 45382:3000
    environment:
      SERVICE_NAME: otravez
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  a99a2194-08bc-45b9-bb88-87b269f0e146:
    container_name: microservice-a99a2194-08bc-45b9-bb88-87b269f0e146
    build:
      context: .
      dockerfile: Dockerfile.a99a2194-08bc-45b9-bb88-87b269f0e146
    ports:
      - 45795:3000
    environment:
      SERVICE_NAME: mundo
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  612efb25-3ddf-483b-9aba-2a8dbb774fa4:
    container_name: microservice-612efb25-3ddf-483b-9aba-2a8dbb774fa4
    build:
      context: .
      dockerfile: Dockerfile.612efb25-3ddf-483b-9aba-2a8dbb774fa4
    ports:
      - 45502:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  13fb6b87-1491-4233-b2c3-bbc01b4e3b6d:
    container_name: microservice-13fb6b87-1491-4233-b2c3-bbc01b4e3b6d
    build:
      context: .
      dockerfile: Dockerfile.13fb6b87-1491-4233-b2c3-bbc01b4e3b6d
    ports:
      - 45832:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  46a2cbc6-bd76-4a57-9311-986bac5538e5:
    container_name: microservice-46a2cbc6-bd76-4a57-9311-986bac5538e5
    build:
      context: .
      dockerfile: Dockerfile.46a2cbc6-bd76-4a57-9311-986bac5538e5
    ports:
      - 45867:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  9c64e5fd-e3e0-4c7d-a483-c824089bf813:
    container_name: microservice-9c64e5fd-e3e0-4c7d-a483-c824089bf813
    build:
      context: .
      dockerfile: Dockerfile.9c64e5fd-e3e0-4c7d-a483-c824089bf813
    ports:
      - 45279:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  3b02d533-fc29-406f-aa81-ad1170284302:
    container_name: microservice-3b02d533-fc29-406f-aa81-ad1170284302
    build:
      context: .
      dockerfile: Dockerfile.3b02d533-fc29-406f-aa81-ad1170284302
    ports:
      - 45492:3000
    environment:
      SERVICE_NAME: hgfjdksl
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  b99dad20-adeb-4b9f-9e48-40f0edd322f9:
    container_name: microservice-b99dad20-adeb-4b9f-9e48-40f0edd322f9
    build:
      context: .
      dockerfile: Dockerfile.b99dad20-adeb-4b9f-9e48-40f0edd322f9
    ports:
      - 45509:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  0f810039-6009-47b6-bcea-198d8eaa08b7:
    container_name: microservice-0f810039-6009-47b6-bcea-198d8eaa08b7
    build:
      context: .
      dockerfile: Dockerfile.0f810039-6009-47b6-bcea-198d8eaa08b7
    ports:
      - 45538:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
  45ff483b-2736-4289-8d21-2faac1774054:
    container_name: microservice-45ff483b-2736-4289-8d21-2faac1774054
    build:
      context: .
      dockerfile: Dockerfile.45ff483b-2736-4289-8d21-2faac1774054
    ports:
      - 45141:3000
    environment:
      SERVICE_NAME: hola
      SERVICE_TYPE: execution
    restart: unless-stopped
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
